### ISSUE TITLE
Image for TuYa TV02 (2.0.4) not parseable

### ISSUE THREAD

**Issue by fettlaus** [Koenkk/zigbee-OTA#104]
Today I intercepted a request upon updating a TuYa TRV TV02 via Tuya Smart Life. The linked binary however sems to not be parseable by ```add.js```. Either I took a completely wrong turn somewhere or the binary is not compatible with the script.
```
PS D:\Workspaces\zigbee-OTA> node scripts/add.js https://images.tuyaeu.com/smart/firmware/upgrade/ay156144560900410bUk/164155152229641863dfc.bin
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
    at new NodeError (node:internal/errors:371:5)
    at boundsError (node:internal/buffer:84:11)
    at Buffer.readUInt16LE (node:internal/buffer:243:5)
    at Object.parseImage (D:\Workspaces\zigbee-OTA\lib\ota.js:17:34)
    at main (D:\Workspaces\zigbee-OTA\scripts\add.js:65:24)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_BUFFER_OUT_OF_BOUNDS'
}
```
Intercepted request:
```yaml
{
    "result": [
        {
            "controlType": 1,
            "currentVersion": "1.0.5",
            "devType": 0,
            "lastUpgradeTime": 0,
            "timeout": 60,
            "type": 3,
            "typeDesc": "ZigBee Module",
            "upgradeStatus": 0
        },
        {
            "canUpgrade": true,
            "controlType": 1,
            "currentVersion": "2.0.0",
            "desc": "In order to cooperate with the upgrade of the Tuya platform, \nthe upgrade will be carried out before the device is used.\nNotes:\n1. Please do not delete or unbind the device  in the APP when upgrading or
upgrade failed, otherwise, the device will be unusable.\n2. Ensure good network when upgrading.\n3. Please do not power off the device when upgrading.\n4. Upgrade failed, the device displays \"---\", please follow the app prompt t☼upgrade again.\n5. If there are multiple temperature control valves, pls upgrade in turn. The device will display \"UP\" when upgrading\n6. After the upgrade, the device will  restart and restore the connection.",
            "devType": 0,
            "diffOta": false,
            "fileSize": "49032",
            "firmwareDeployTime": 1645523068,
            "lastUpgradeTime": 0,
            "md5": "5a416bf477da3330aae8b9f56a8c90e1",
            "timeout": 60,
            "type": 9,
            "typeDesc": "MCU Module",
            "upgradeStatus": 1,
            "upgradeType": 0,
            "upgradingDesc": "Please keep the power of the device connected during the upgrade process, please be patient.",
            "url": "https://images.tuyaeu.com/smart/firmware/upgrade/ay156144560900410bUk/164155152229641863dfc.bin",
            "version": "2.0.4"
        }
    ],
    "status": "ok",
    "success": true,
    "t": 1648976003782
}
```
